sudo: no

language: python

env:
  - TOXENV=flake8

matrix:
  fast_finish: true
  include:
    - python: 2.7
      env: TOXENV=py27-1.8
    - python: 2.7
      env: TOXENV=py27-1.9
    - python: 2.7
      env: TOXENV=py27-1.10
    - python: 2.7
      env: TOXENV=py27-1.11

    - python: 3.4
      env: TOXENV=py34-1.8
    - python: 3.4
      env: TOXENV=py34-1.9
    - python: 3.4
      env: TOXENV=py34-1.10
    - python: 3.4
      env: TOXENV=py34-1.11

    - python: 3.5
      env: TOXENV=py35-1.8
    - python: 3.5
      env: TOXENV=py35-1.9
    - python: 3.5
      env: TOXENV=py35-1.10
    - python: 3.5
      env: TOXENV=py35-1.11

    - python: 3.6
      env: TOXENV=py36-1.11

install:
  pip install tox coveralls

script:
  tox

after_success: coveralls
